### ISSUE TITLE
Request for information (mills/micros overflow issue is there/not)

### ISSUE THREAD

**Issue by mutthunaveen** [sstaub/Ticker#11]
Dear Sstaub

This is not an issue. i just wanted to know if mills() or Micros() overflow will not happen when i use this ticker?? using your library never misses a schedule/callback for life?? is code is developed in such a way that overflow of mills and micros will not miss any "call back"

is it safe to use?

im trying to implement this code in my water controller. 
i feel my project is critical as this is going to be controlling 1hp motor ON and OFF. im using ticker to scan inputs for every 100ms and some inputs in 10ms and some inputs in 1000ms and based on those 3 inputs im switching ON and OFF my motor.

please release my anxiety. Thank you

**Comment by sstaub** [comment]
There is no overflow problem with callbacks.
