### ISSUE TITLE
Callback name

### ISSUE THREAD

**Issue by AlexFundorin** [sstaub/Ticker#12]
Why can't I use NULL in place of a callback name? I don't need ticker to call any function. All I need is to get elapsed time (millis) from the moment I started the timer and nothing else.

**Comment by sstaub** [comment]
uint32_t startTime = millis();
uint32_t elapsedTime = startTime - millis();
Why did you need this library?

**Comment by AlexFundorin** [comment]
Ability to stop, pause and resume timer. 
Why did you close this issue? Did you fix it, already?

**Comment by sstaub** [comment]
If you have a solution make a PR. You can do also a dummy callback function.

**Comment by AlexFundorin** [comment]
This is exactly what I was using. 
`void blank(){};`
