### ISSUE TITLE
function isn't a type name

### ISSUE THREAD

**Issue by AlexFundorin** [sstaub/Ticker#13]
When I'm declaring a timer inside main.cpp, everything is fine. Yet, as soon as I try to declare it inside a class, I get the following.
https://i.imgur.com/Kk6i9Uy.png
```
void blank(){};
Ticker timer1(blank, 1);
```

**Comment by sstaub** [comment]
Were did you declare the function blank?

**Comment by AlexFundorin** [comment]
I tried declaring it in several places:
main.cpp before loop
main.cpp before ticker include
inside the class (header file) right before the timer object
inside the same header file, but as a class function outside the class itself.

**Comment by sstaub** [comment]
It sounds like a generell problem of nested classes. You should look in the web for it.

**Comment by AlexFundorin** [comment]
Thanks for the suggestion.
For those, who'd encounter the same situation and doesn't need callback functionality, there's a [Chrono library](https://github.com/SofaPirate/Chrono), which is working fine in the same conditions.
