### ISSUE TITLE
Improvements request

### ISSUE THREAD

**Issue by SergiuToporjinschi** [sstaub/Ticker#14]
Hi,
First of all, nice lib. Helps me a lot.
* It would be nice if you can add a function to return the interval that is used for ticker. It seems to be not a very big thing but helps me a lot. In a more complex architecture with multiple ticker instance I will not have to keep my self the last interval for each ticker for the case where I need to return information about one of the tickers;
the function that I need can look like : 
```cpp
uint32_t Ticker::getInterval() {
    if (resolution == MICROS) {
        return this->timer / 1000;
   } else {
        return this->timer;
   }
}
```

* Another optimization will be to define the enums by specify the storage as :uint8_t, will earn about 3 bytes for each element in enum, for this library will earn about 21bytes :) :
```cpp
enum resolution_t:uint8_t {MICROS, MILLIS, MICROS_MICROS};
```
```cpp
enum status_t:uint8_t {STOPPED, RUNNING, PAUSED};
```

* Other thing will be, but maybe you already thought on this, to go in a direction to create a list of tickers. I think most of the developers are not using this lib for just one ticker but for multiple ones. Maybe worth to manage a list of tickers and the developers to register a ticker 

Maybe you are to busy for this changes, if you want I can branch this and do the changes but I don't like to keep projects on which I'm not the owner; plus that I want to be up to date with your changes in this lib. So, if I'm doing the changes can you merge them?

**Comment by sstaub** [comment]
Thank's for your interest.
- the function you search, like other ones, can you find in v2.10 in the releases
- enum optimization, I want to avoid compiler (C++11) specific optimization,
I don't know what the size of enum, but an int on AVR is 16bit.
The goal of this library was to keep simple things very simple, so I
decided with v3.xx to simplify the API.
So, feel free to make your own version of thicker.
