### ISSUE TITLE
Get time left until execution?

### ISSUE THREAD

**Issue by ghoeffner** [sstaub/Ticker#18]
I see that there is a function to get the number of times it has been executed, but in my case I want to see how much time is left on the timer in order to be able to "top up" the timer again (remaining time + x as the new interval).

Is there any way to achieve this?

**Comment by sstaub** [comment]
uint32_t elapsed(); gives you the time after the last execution.

**Comment by ghoeffner** [comment]
"Returns the time passed since the last tick, ms or us depending from the resolution." seems to be a quiet complicated description for this!

Great to know, thanks for your quick help. elapsed() works perfectly fine for my use-case!
