### ISSUE TITLE
error in readme.md

### ISSUE THREAD

**Issue by stef-ladefense** [sstaub/Ticker#39]
examples

Tickers timer(blink, 1000); // calls function blink() every second, internal resolution is **micros**, running endless
Tickers timer(blink, 1000, 5); // calls function blink() every second, internal resolution is **micros**, only 5 repeats

micro ? sure ? 

Tickers timer(blink, 1000, 0, MILLIS); // calls function blink() every second, internal resolution is millis, running endless
Tickers timer(blink, 1000, 0, MICROS_MICROS); // calls function blink() every 1000 microsecond, internal resolution is micros, running endless

**Comment by sstaub** [comment]
internal resolution is micros() as standard

**Comment by stef-ladefense** [comment]
you write 
mode set the interval resolution to **MILLIS (default)** or MICROS
it's wrong then ?

**Comment by sstaub** [comment]
It was MICROS and I correct the readme.

**Comment by stef-ladefense** [comment]
Good ! merci
