### ISSUE TITLE
Ticker remaining() error.

### ISSUE THREAD

**Issue by zeehond1** [sstaub/Ticker#47]
At least in version 4.2.0.
For MILLIS initiaslisation there is an error within the function remaining().

    ticker_midnight=new Ticker(__midnight, mid_start * 1000L, 1, MILLIS); 
The function remaining() is a substraction of the initialised value timer and 
the result fo function elapsed().
The value timer has ofcourse already the value in MILLIS (as initialised) 
and also the function elapsed() is in the right value by function millis().

 uint32_t Ticker::elapsed() {
	if (resolution == MILLIS) return millis() - lastTime;
	else return micros() - lastTime;
	}

So the divide by 1000 in function remaining() is not needed and gives now 
wrong values when used as it is now:

return timer / 1000 - elapsed();

Please adapt considder to adapt the function remaining() to:

uint32_t Ticker::remaining() {
	return timer - elapsed();
	}

Test example:
#include <Ticker.h>

Ticker *ticker_minute;

void __minute(void)
  {
  Serial.println("__minute(): The end.");
  }

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  while (!Serial);

  ticker_minute=new Ticker(__minute, 60 * 1000L, 1, MILLIS);

  }

void loop() {
  // put your main code here, to run repeatedly:

  ticker_minute-> update();
  Serial.print("remaining: ");
  Serial.println(ticker_minute->remaining());
  Serial.print("elapsed: ");
  Serial.println(ticker_minute->elapsed());
  }

givves as output:

13:25:53.924 -> remaining: 4294929916
13:25:53.924 -> elapsed: 97382
13:25:53.924 -> remaining: 4294929913
13:25:53.924 -> elapsed: 97385
13:25:53.924 -> remaining: 4294929909
13:25:53.924 -> elapsed: 97389
13:25:53.924 -> remaining: 4294929906
13:25:53.924 -> elapsed: 97392
13:25:53.924 -> remaining: 4294929902
13:25:53.924 -> elapsed: 97395
13:25:53.924 -> remaining: 4294929899At least in version 4.2.0.
For MILLIS initiaslisation there is an error within the function remaining().

    ticker_midnight=new Ticker(__midnight, mid_start * 1000L, 1, MILLIS); 
The function remaining() is a substraction of the initialised value timer and 
the result fo function elapsed().
The value timer has ofcourse already the value in MILLIS (as initialised) 
and also the function elapsed() is in the right value by function millis().

 uint32_t Ticker::elapsed() {
	if (resolution == MILLIS) return millis() - lastTime;
	else return micros() - lastTime;
	}

So the divide by 1000 in function remaining() is not needed and gives now 
wrong values when used as it is now:

return timer / 1000 - elapsed();

Please adapt considder to adapt the function remaining() to:

uint32_t Ticker::remaining() {
	return timer - elapsed();
	}

Test example:
#include <Ticker.h>

Ticker *ticker_minute;

void __minute(void)
  {
  Serial.println("__minute(): The end.");
  }

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  while (!Serial);

  ticker_minute=new Ticker(__minute, 60 * 1000L, 1, MILLIS);
  ticker_minute->start();
  }

void loop() {
  // put your main code here, to run repeatedly:
  static int e=0, el;

  el=ticker_minute->elapsed();
  if(e!=el/1000)
    {
    e=el/1000;

    ticker_minute-> update();
    Serial.print("remaining: ");
    Serial.println(ticker_minute->remaining());
    Serial.print("elapsed: ");
    Serial.println(el);
    }
  }

gives as output:
15:48:49.419 -> elapsed: 55000
15:48:50.444 -> remaining: 4294911356
15:48:50.444 -> elapsed: 56000
15:48:51.436 -> remaining: 4294910356
15:48:51.436 -> elapsed: 57000
15:48:52.428 -> remaining: 4294909356
15:48:52.428 -> elapsed: 58000
15:48:53.420 -> remaining: 4294908356
15:48:53.420 -> elapsed: 59000
15:48:54.445 -> __minute(): The end.

expected output:
15:38:29.168 -> remaining: 3000
15:38:29.168 -> elapsed: 57000
15:38:30.160 -> remaining: 2000
15:38:30.160 -> elapsed: 58000
15:38:31.153 -> remaining: 1000
15:38:31.153 -> elapsed: 59000
15:38:32.178 -> __minute(): The end.

Thanks

Ed Faber
Netherlands.
13:25:53.924 -> elapsed: 97399
13:25:53.924 -> remaining: 4294929896
13:25:53.924 -> elapsed: 97402
13:25:53.924 -> remaining: 4294929892
13:25:53.924 -> elapsed: 97405
13:25:53.924 -> remaining: 4294929889
13:25:53.924 -> elapsed: 97409

Thanks

Ed Faber
Netherlands.

**Comment by sstaub** [comment]
Solved with 4.3.0
