### ISSUE TITLE
how to call a function with arguments

### ISSUE THREAD

**Issue by jcherrabi** [sstaub/Ticker#48]
Hello there,
can you please share a way we can call a function and pass it a parameter?
i tried the lambda but i'm getting error..
`Ticker smyFunc([](char i)
                           { funcToCall(i); },
                           1, 1);`

thank you,
Jay

**Comment by sstaub** [comment]
There is an example which using lambdas. Using functional was an PR not from me.

**Comment by jcherrabi** [comment]
yes i just saw that, thank you :)
