### ISSUE TITLE
Code may not work properly after running for 50 days straight

### ISSUE THREAD

**Issue by marco7m** [sstaub/Ticker#49]
The timers are based on the millis() and micros() functions from arduino, but reading the description of the millis() function on the arduino reference page:

"Returns the number of milliseconds passed since the Arduino board began running the current program. This number will overflow (go back to zero), after approximately 50 days." ([reference](https://www.arduino.cc/reference/en/language/functions/time/millis/)

I found that after 50 days this function will go back to zero, and the code may malfunction.

**Comment by sstaub** [comment]
The library should work as expected after overflow. What is the malfunctiom?
