### ISSUE TITLE
Cannot load Ticker.h library (conflicts with the default Ticker.h library)

### ISSUE THREAD

**Issue by iotindustries** [sstaub/Ticker#50]
Hi, I am using Arduino IDE 1.8.15 and that has a default library called Ticker.h. I installed your library, but if I try to use it, Arduino IDE refers to the default Ticker.h library and not yours. So it says error such as "error: 'class Ticker' has no member named 'start'", "error: 'class Ticker' has no member named 'update'", "'class Ticker' has no member named 'remaining'". Is there any solution for this issue? Thank you.

**Comment by sstaub** [comment]
Ok, it seems you use an ESP. You must rename the Library items.

**Comment by iotindustries** [comment]
Yes I use ESP. Can you please tell me what exactly do I need to rename? I renamed the Ticker.h and Ticker.cpp to TickerESP.h/TickerESP.cpp but arduino IDE cannot recognize it. Thank you.

**Comment by sstaub** [comment]
In the .cpp you must also change the `#include "Ticker.h"` to `#include "TickerESP.h"`

**Comment by iotindustries** [comment]
Renaming the #include solved the issue. Thanks.

**Comment by sstaub** [comment]
have a look to the TickTwo library
