### ISSUE TITLE
Would a 'Ticker::remaining_count()' function be viable?

### ISSUE THREAD

**Issue by georgevbsantiago** [sstaub/Ticker#52]
Hi, Thank you so much for this library

I tried to make an Inverted Counter with Ticker to find out how many repetitions are left, but I didn't find a specific function.

I saw that there is the function Ticker::remaining(), to return the remaining time to the next tick in ms or us depending on mode.

Would it be feasible to implement a Ticker::remaining_count() function to returns the remaining count?

I believe this function would be useful to countdown to apply in other functions or in Serial.Print, display/LCD...

Something like:
Current tick: `Ticker::counter()`
Remaining tick: `Ticker::remaining_count()`

I tried to do it like this (sorry,I'm a beginner in Arduino and ESP):

```
Ticker displayLCD_countdown_TICKER(displayLCD_countdown, 1000, 60, MILLIS);

displayLCD_countdown(){

int countdown = 60 - displayLCD_countdown_TICKER.counter();

Serial.print(countdown);
Serial.println(" attempt left");

}
```

But it's not a good solution. If the number 60 is changed in just one place, an error may occur.

**Comment by sstaub** [comment]
Your solution gives what you want. Because the number of remaining counts can be endless, a special function will not a good idea.
